### PR TITLE
Add support for custom WordPress roles

### PR DESCRIPTION
**Pull request by phille97**
Add ability to map WordPress roles other than the standard 5

### CODE REVIEW

**Comment by ktbartholomew** [comment]
@phille97 This looks great, thanks for the PR! I need to make sure I have a clear path for getting changes from GitHub to the Wordpress SVN repo, as this will be the first change published since I moved the code here. I'll merge and cut a new release once I figure all that out.

**Comment by phille97** [comment]
https://gist.github.com/kasparsd/3749872#pushing-changes-to-wordpress-subversion-repository ;)

**Comment by ktbartholomew** [comment]
@phille97 Thanks for the bump :) :shipit:

**Comment by ktbartholomew** [comment]
@phille97 I finally worked through my SVN troubles (turns out parts of SimpleSAMLPHP have syntax errors under PHP 5.4) so version 0.9.4 has now been published, including your changes.  Thanks for the contribution!

**Pull request merged**
